[package]
name = "libcounter"
version = "0.1.0"
authors = ["Eric Haskins <eric@ehaskins.com>"]

[dependencies]
wasm-bindgen = "0.2.24"
console_error_panic_hook = "0.1.3"

[lib]
crate-type = ["cdylib", "lib"]
